### ISSUE TITLE
VASL6.7.1 and VASSAL3.7.16

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#2019]
Gordon is working on cleaning up initial bugs found in counters due to the svg conversion. 

My thought would be to issue those changes as 6.7.1-beta1 as soon as possible, including any and all other changes pushed to develop since 6.7.0 has been issued. 

I will build 6.7.1-beta1 using VASSAL3.7.15 to limit the amount of change going on. 

Once 6.7.1-beta1 issues, we should then switch to using VASSAL3.7.16 for dev. 

Any concerns?

**Comment by geezer09** [comment]
So this has been discussed on GS forums but I think it deserves attention here as well. The 6.7.0 release has a pretty major issue with 5/8 concealment counters basically not working. I didn't do any digging into why they were not working but only noticed that they seem to not conceal 5/8 counters for the owning player and then maybe hide them to the opponents?

I think Gordon has fixed the issue but I think this particular issue will make 6.7.0 almost useless. 5/8 concealment counters not working is a pretty major bug. My two questions are:

1) How was this not found out in beta? Almost every scenario has guns with 5/8 concealment counters. It seems like this should have been picked up. I think we need to be a bit more dilligent with testing, even if that only means giving beta releases more time between releases. My impression is that we have been doing too much too quickly and it is biting us. Maybe we should try slowing down the rate of features and focus on quality over quantity.

2) What should we do with 6.7.0? In my opinion that concealment bug will make it unpopular and it needs a fix. @GordonMolek you seem to have been able to fix this functionality but are having issues with the displaying of the mini ?. Why can't you do whatever you did with the 1/2 counters? If you can get it to display properly then maybe we can release a quick beta with only this fix for testing and then release 6.7.1?

**Comment by GordonMolek** [comment]
I am not sure I follow. AFAIK, concealment works properly in the intended
6.7.1 beta 1 now.

**Comment by geezer09** [comment]
What I meant is that the functionality seems to work but the image quality is low for the mini ?.

**Comment by derimmer** [comment]
I am going to answer the second set of questions first because I think they are more important. 

> 2. What should we do with 6.7.0? In my opinion that concealment bug will make it unpopular and it needs a fix. [@GordonMolek](https://github.com/GordonMolek) you seem to have been able to fix this functionality but are having issues with the displaying of the mini ?. Why can't you do whatever you did with the 1/2 counters? If you can get it to display properly then maybe we can release a quick beta with only this fix for testing and then release 6.7.1?
>
@GordonMolek has fixed a number of bugs, including the  "disappearing counter/no concealment" 5/8 concealment issue and has pushed the changes up to github. I think it is ready to go as a beta and as per my initial post, I think that should go out asap so I will build and release it either tonight or tomorrow.

This will not include a fix for the mini ? issue. To be clear, Gordon has fixed the problem with it not appearing at all. What should wait for later betas/versions, IMO, is the quality of the mini ? image. That does not need a short-term fix.

As for releasing a 6.7.1 official version as soon as we are sure the beta has fixed the major concealment issues, I personally am content to wait until the planned release this fall and let people use the beta (which will contain almost no other changes - beyond @geezer's  "Make A Suggestion" feature). When we have released new versions on the heels of new versions in the past, we get a certain amount of flak for "too many damn versions". 

But that is just my opinion. Any one of us is free (and indeed, I would encourage you) to build and release a new version at any time. @geezer has created some workflows that are very helpful. There are instructions on the Wiki page. So, if anyone thinks a quick release of the official version of 6.7.1 is a good idea, by all means go ahead.   
>
> 1. How was this not found out in beta? Almost every scenario has guns with 5/8 concealment counters. It seems like this should have been picked up. I think we need to be a bit more dilligent with testing, even if that only means giving beta releases more time between releases. My impression is that we have been doing too much too quickly and it is biting us. Maybe we should try slowing down the rate of features and focus on quality over quantity.
> 
I don't know why it wasn't. Our beta testing protocols are loose to the point of non-existence. LOL! We throw betas out, hope they get some feedback and move on. Can we do better? Of course. 

To some extent, we are the victims of our own success. The changes (features and fixes) that we have made have created an appetite for more, more, more. And @geezer's Make A Suggestion is going to make it easier for people to submit issues. All of this is great. But @geezer09 is right to ask, in the face of that, should we alter our current beta/official version practice and timing. 

I am ok with going to one version a year and being more rigorous with testing. Personally, I intend to focus on los issues for the rest of the year. 

Final point: IMO, people should work on the issues, whether features or bugs, that they want to work on, regardless of user requests. We are volunteers not employees.

**Comment by uckelman** [comment]
> When we have released new versions on the heels of new versions in the past, we get a certain amount of flak for "too many damn versions".

I wouldn't put much store in that complaint when it comes from people who contributed no time testing before a release. On the other hand, holding up a release when you have bug fixes from which users could benefit is a real problem.

**Comment by derimmer** [comment]
As per my post above, I have built 671-beta1. It is available on the github releases page. Plus, I have updated the [VASL.info/VASL](https://vasl.info/vasl_coop.htm) page where I put info about beta releases. 

I have NOT yet announced this on GS, FB, or Discord because of the following:

![Image](https://github.com/user-attachments/assets/4ec9e88c-77f1-4c88-9c56-56f4bcc21a93)

As you can see there is a Bad Data in Module message (which users always fine troubling) but the MOVED tag appears as it should. 

I did not notice this error when I built the module locally before pushing changes to github and building there. I have left the release up on Github and VASL.info for now. Not many, if any, will find it without a prompt. @GordonMolek can you have a look at this Bad Data" bug?

NOTE: Also as per my post above, I have updated the POM.xml file to use VASSAL3.7.16 when building future VASL versions. Again, I pushed this change, before noticing the Bad Data bug. I have also started using Open JDK v24 in my local dev environment.

**Comment by GordonMolek** [comment]
Doug,
I have the fix (2 lines changed in the buildFile), sorry about that. Should
I just check it in, send you the buildFile, or the whole VMOD?

Gordon

**Comment by derimmer** [comment]
Gordon, check in the fix (and bump the version in the buildFile to 6.7.1-beta2). 

I will revert to VASSAL3.7.15, and then build and release 671-beta2. I will delete the beta1 release from the Releases page.

**Comment by GordonMolek** [comment]
Doug,
I've updated line 2 of the buildFile to beta2. But what about this line?

"<VASSAL.build.module.documentation.BrowserPDFFile pdfFile="Whats New
VASL671-beta1.pdf" title="What's New"/>"

and is there anywhere else that it needs to be updated? I'm still not
completely caffeinated yet.

Gordon

**Comment by derimmer** [comment]
Yes, bump it to beta2 where it says beta1. Good catch!
________________________________

**Comment by derimmer** [comment]
I have released beta2 on the github releases page and updated VASL.info.

I will announce it on FB etc later today. Got to go back to RL for a while.

**Comment by GordonMolek** [comment]
Awesome, thanks! I hope I didn't screw anything else up and I'll certainly
be more surgical and careful with any changes I make.

**Comment by derimmer** [comment]
We learn by error! LOL.

**Comment by GordonMolek** [comment]
I'm an effin' Einstein, then.

**Comment by GordonMolek** [comment]
For anyone interested in chipping in, I've created issue 2036 - Investigate
and correct "concealed to me" mini-? counter rendering issue.

One thing I can't seem to figure out, not being a Java programmer, is why
VASSAL/VASL seems to be rendering the mini-? and covering translucent
counter as raster rather than vector graphics.

**Comment by geezer09** [comment]
I think I have mentioned this before, but I will say it again. When releasing new versions (beta or otherwise) I strongly urge whoever is releasing to not simply create a pull request and merge immediately. Please leave that PR open for at least a day.

Within the PR is the perfect place to discuss and make little last minute testing and changes like that bad data in module bug. I think this last beta release did not unlock the feature for making suggestions I have implemented and was removed from the buildfile for 6.7.0

**Comment by GordonMolek** [comment]
Sorry. I will endeavor to remember. Is there an "official"
process/procedures document that I can have to hand for next time?

**Comment by derimmer** [comment]
@Gordon this is entirely on me. I was the one who built both beta releases. 

@geezer09 I understand what you have asked. But I also read your note upthread, where you wrote "maybe we can release a quick beta with only this fix for testing". That is what I was trying to do. And so, I created the pull request and decided to merge it right away as part of being quick. I am more than happy to leave pull requests for new versions open for a while. Just a misunderstanding on my part.

**Comment by derimmer** [comment]
I have pushed up the revised pom.xml, setting the VASSAL version to 3.7.16.

In doing so I realized that although this is issue #2019, I have flagged all the pushes-and-pulls I have done related to it as related to vasl-developers/vasl#2020. I cannot explain why; just stupid is why. 

I will leave this issue open for the next few days to allow anymore comment on the broader issues of managing PRs. Beyond that, it is time to close this one.

**Comment by GordonMolek** [comment]
Gentlemen (at least I don't know of any women on this thread),
I am preparing another round of counter fixes as well as the new Slaughter
at Ponyri counters. I would like to add these to 6.7.1 beta 3. I want to do
so without publishing them yet. So that I understand proper Git terminology
going forward, what are the steps I should take. I was planning on doing so
on the main development branch since there will be no code changes. If that
is an incorrect approach, please let me know as well.

Thanks,

Gordon

**Comment by geezer09** [comment]
I can walk you though it. There are no code changes? Do you mean all changes are within the buildfile?

**Comment by GordonMolek** [comment]
Yes, since I've hit a wall in the "concealed to me" rendering issue, I will
only be committing new and changed image files and a corresponding updated
buildFile. Obviously, I've performed all of the steps, but just want to
make sure I stop before I force these changes on any other developer/the
user community before their time.

**Comment by geezer09** [comment]
I’m not quite sure what your intentions are. If you want to create beta 3 without releasing it, just push your changes to the develop branch, i’ll then show you the step-by-step process.

**Comment by GordonMolek** [comment]
Yes, I want to commit my changes for what will be (in part) beta 3, but I
don't want to release it yet as I will be working on more fixes, additions
and want to allow others who have fixes/changes to have time to get their
stuff in.

**Comment by geezer09** [comment]
Okay well in that case you can create a branch from the develop branch and then push all your code to that branch. Once we create beta 3 we will simply merge that back into the develop branch.

**Comment by GordonMolek** [comment]
How do I reformat a "VASL Counters" palette tab to have 4 columns rather
than 3? I thought that a good place to add the SaP "Train OBA" counters
would be in the "Other->OBA" tab/panel, along with the Red/Green/Blue OBA
counters. I think we'll only need the AR/FFE1/FFE2/FFEC counter and the
Offbd Observer counter, so I thought I'd add them as a new right-most
column with placeholder entries to keep everything lined up. Alternatively
I could just put it in the bottom row, or somewhere else entirely if the
hive-mind decides on someplace.

Also, I was thinking that the SaP "Mine Belt" counters would be able to
flip directions like the existing known minefield counters, reveal their
strength like the existing AP/AT minefield counters, and the "strength"
option would just cycle between "6 AP/12 AP/2 AT/4 AT" rather than having
separate AP/AT versions. Thoughts?

**Comment by derimmer** [comment]
@GordonMolek I once tried to play with the columns in the draggable overlays window. It did not go well and I gave up. But I think the way to do it is to navigate to the node for the panel or tab that you want to change in the main editor window and then right-click on the panel or tab and I think you get a popup that should let you change things. That is what i am remembering.

As for your other comments, I have no difficulty with anything you suggest. It all sounds fine to me.

**Comment by GordonMolek** [comment]
That's it! Worked like a champ. Thanks.

I think I've got the Mine Belt counters sussed out and then I just need to
make a matching "Train OBA" offboard observer counter and then I think I'll
be looking for volunteers to give it a test drive to see if the counters
work like they're supposed to.

**Comment by GordonMolek** [comment]
I was looking to nail down the files I need to check in for the current
crop of identified counter fixes, enhancements and the SaP files and
noticed that I am suddenly seeing lots (potentially all) of the generated
SVG files are showing as differing with the repository in the line
separators used. The repository seems to have versions with CRLF and my
local copies only have LF. Is that expected? If so, is there a setting to
ignore said trivial differences?

**Comment by derimmer** [comment]
Hi Gordon

It may be an IDE setting and those images that passed through my device
inherited my setting?

Honestly that is just a guess. I’d not even know what my default settings
are.

Doug

**Comment by GordonMolek** [comment]
OK, I found this:
https://www.jetbrains.com/help/idea/configuring-line-endings-and-line-separators.html

I'm just not sure what approach we want to take to minimize file churn in
the future.

**Comment by GordonMolek** [comment]
What's even weirder is that some of my generated files are showing lines
ending with just LF white others have lines ending with CRLF.

**Comment by GordonMolek** [comment]
OK, what seems to be happening is that the files are "generated" with
Unix-style LF-only. But when I edit any files with Notepad++ the settings
are to use CRLF. So which way do we want to go and I'll either adjust my
generation code or my Notepad++ settings.

**Comment by geezer09** [comment]
I see you are just getting familiar with line endings and have probably never had to deal with issues these can create. 

I’m not to sure what you are working on but I would strongly suggest you do not modify them.

**Comment by GordonMolek** [comment]
I'm familiar with line endings, I've just never really worked in a mixed
environment like Cygwin on Windows with IntelliJ and DOS command line and
whatever (if anything) GitHub might be doing. I'd like to clean things up
and have it be consistent, so I will go with CRLF for all SVG files. That
will hopefully not generate a huge commit since the repository seems to be
in that "flavor" and I won't get massive numbers of trivial line ending
differences every time I go to commit changes.

**Comment by zgrose** [comment]
FWIW, the `.gitattributes` file can do the normalizing for you.

https://docs.github.com/en/get-started/git-basics/configuring-git-to-handle-line-endings

I wouldn't worry about the number of files in a commit. If I see a commit message that says "normalize line endings in svg files" and it has 6000 files touched, I would be pretty happy. If you snuck in 1 or 2 .java edits in the same commit, that would make it an annoying commit.

**Comment by GordonMolek** [comment]
Note to self, keep this in my back pocket for the perfect opportunity. 😉😁

**Comment by derimmer** [comment]
@geezer09 I merged the pull request and all seemed well. The draft release was created on github. Before publishing it I downloaded  the .vmod from the page and ran it. A VASSAL error showed up, and the bug report includes the following

at VASSAL.build.Builder.create(Builder.java:118)
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: Unable to load class org.bouncycastle.jce.provider.BouncyCastleProvider
	at VASSAL.tools.DataArchive.findClass(DataArchive.java:463)
	at VASSAL.tools.DataArchive.loadClass(DataArchive.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528)
	... 29 common frames omitted
Caused by: java.io.FileNotFoundException: 'org/bouncycastle/jce/provider/BouncyCastleProvider.class' not found in C:\Users\DougR\Downloads\vasl-6.7.1-beta3.vmod
	at VASSAL.tools.DataArchive.getInputStream(DataArchive.java:179)
	at VASSAL.tools.DataArchive.findClass(DataArchive.java:459)

I have left the draft release in place on the releases page. You should be able to see it there and download it. 

@GordonMolek there may be a short delay in releasing beta3.

**Comment by geezer09** [comment]
Okay will look into this

**Comment by geezer09** [comment]
Okay i sort of fixed it ( i think). The issue creator is still not working but that was kind of expected. Can you try redownloading the vmod file and giving it a try?

**Comment by derimmer** [comment]
Was able to download and run. It opened without an error. I opened a saved game, no issue. Tried to submit a suggestion. When I clicked sumbit, I got the following. 

![Image](https://github.com/user-attachments/assets/eb00f055-cf5f-44c8-82b0-40fa37e80615)

So close!

Do you want to work on this some more? There is no rush to get beta3 out. I am playing in a ASL tournament Fri-Sun so if not today then you have until at least Monday. But downloading from the Draft Release page seems to be a good way to test changes, if somewhat laborious. Can you see that page?

**Comment by GordonMolek** [comment]
That seems like it is working the way every suggestion box I've ever seen
works. Basically puts the suggestion into the trash. 🤔

Doug,
I don't know if this attempt would have picked up the British SW changes I
checked in yesterday. If not, and you delay, can you pick those up as well?
If not, no worries.

**Comment by derimmer** [comment]
If you checked them into develop then they should have been picked up.

**Comment by geezer09** [comment]
I am currently working on the issue creator but i noticed there are issues with a few counters from the tool bar. Smoke, prisoners, random white counter (work, TI) dont seem to display.

**Comment by GordonMolek** [comment]
I will take a look.

**Comment by GordonMolek** [comment]
Interesting, everything seems to display properly for me. I tried both my
current development VMOD and the pending release from the server.

**Comment by geezer09** [comment]
You are absolutely correct, the version on git seems to be fine. It seems like something I am doing with the Issue creator is somehow affecting the counters? How is that even possible ....

**Comment by GordonMolek** [comment]
Maybe the same way that the game updater started having problems when SVG
counters were introduced? I dunno.

**Comment by geezer09** [comment]
Okay, I think everything is working reasonably well right now. I re-uploaded the .vmod file for beta 3. Please try to redownload and make sure everything seems normal. Make a quick check of counters, especially any newer SVG ones and try to submit an issue to see if that works.

**Comment by GordonMolek** [comment]
Thanks, will do.

**Comment by derimmer** [comment]
I was able to download and open beta3. No issues. Submitted a suggestion successfully. Looked at the British mortars. Seemed ok to me. dragged some counters off the tool bar. 

Looks like it is ready to go. I am off for pre-tournament drinks. I might have time to release beta3 when I get back tonight but if either of you want to go ahead (and have the necessary github permissions), go right ahead. I usually post a notice in GS, FB, and Discord.

**Comment by geezer09** [comment]
Is this the CASLO? I’m jealous. Good luck, and have a great time!!
________________________________

**Comment by derimmer** [comment]
It is indeed. Thanks. Going to release beta3 now.

**Comment by GordonMolek** [comment]
I'm not sure if there's a general purpose discussion place, but I figured I'd ask here since it is at least tangentially related to SVG implementation. If one where crazy/stupid enough to want to create SVG-based die graphics and integrate them into ASLChatter, how would one go about it? I see where the code is apparently constructing HTML to reference the dice images, but if I substitute SVG file references the "alt_text" gets displayed. Does ASLChatter not handle SVG images? If not, can someone point me to what/where I would need to change to have it do so? I was thinking of adding a preference for "legacy dice graphics" (on by default) that would preserve the existing graphics.

**Comment by BigAl737** [comment]
Hi Gordon, I did the chatter dice in SVG and provided the png versions to Doug. Would it help you to have the SVG chatter dice file?

**Comment by GordonMolek** [comment]
So you have Java code specifically to handle SVG dice images? If so, I'll
take 2. 😉

**Comment by BigAl737** [comment]
Java? Me? I Speak ‘mercian. I’m not smart enough to speak Java. I can send you the SVG file I used to create the dice art if you’d like. I figure there’s no need to create those again.

**Comment by derimmer** [comment]
@GordonMolek 

Are these the code segments you are referring to:

public interface ASLDie {

  final static String DIE_FILE_NAME_FORMAT = "DC%s_%s.png";

  public String getDieHTMLFragment(final int roll);
}

public class ASLColoredDie implements ASLDie{
  DieColor color;
  public ASLColoredDie(DieColor color){
    this.color = color;
  }
  @Override
  public String getDieHTMLFragment(int roll) {
    return String.format(DIE_FILE_NAME_FORMAT, String.valueOf(roll), color);
  }
}

It would appear to me that the only changes necessary to implement svg for dice images would be to changed the value of DIE_FILE_NAME_FORMAT to "DC%s_%s.svg".  Is this what you tried?

Of course, the svg image files would have to be placed in dist/images/dice. Or the code would have to be pointed to wherever they are. 

If you want to send me a couple of svg images I can debug the code and see where it isn't working. I think the html string is getting messed up. That is what usually generates the alt_text message,

**Comment by GordonMolek** [comment]
Doug,
That looks like what I was trying to change. I will send you (separately)
the SVG files for the white die to play with. I was indeed thinking of
putting them in "images/dice" as opposed to "images" where the current PNG
versions reside.

Thanks,

Gordon

**Comment by derimmer** [comment]
Gordon

I have totally failed on this one. Just got caught up in other things and lost sight of it. Do we want to put this in beta4 or leave it for beta5?

I will move it to the top of my list.

**Comment by GordonMolek** [comment]
No problem, a lot's going on. Beta 4 is fine.

**Comment by GordonMolek** [comment]
Sorry, meant to say beta 5!!!

**Comment by derimmer** [comment]
Safe to close this one for now.
